_BASE_: BASE_VATEX.yaml
MODEL:
  BACKBONE:
    NAME: "VideoSwinTransformerBackbone"

  VIDEO_SWIN:
    VERSION: "video_swin_b_p4w7"
    #USE_CHECKPOINT: True
  WEIGHTS: weights/video_swinb_v2.pkl
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

DATASETS:
  TRAIN: ("refcoco_train","refcoco+_train", "refcocog_train")
  TEST: ("refcoco_val",  "refcoco_testA", "refcoco_testB", "refcoco+_val", "refcoco+_testA", "refcoco+_testB", "refcocog_val", "refcocog_test")
  # TEST: ("refcocog_val",)

INPUT:
  SAMPLING_FRAME_NUM: 4

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (70000, )
  MAX_ITER: 100000

TEST:
  EVAL_PERIOD: 5000