_BASE_: BASE_VLFormer.yaml
MODEL:
  BACKBONE:
    NAME: "VideoSwinTransformerBackbone"

  VIDEO_SWIN:
    VERSION: "video_swin_t_p4w7"
    #USE_CHECKPOINT: True
  WEIGHTS: "weights/video_swin_t.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

DATASETS:
  TRAIN: ("refcoco_train","refcoco+_train", "refcocog_train")
  TEST: ("refcoco_val",  "refcoco_testA", "refcoco_testB", "refcoco+_val", "refcoco+_testA", "refcoco+_testB", "refcocog_val", "refcocog_test")
  #TEST: ("refcoco_val",)
INPUT:
  SAMPLING_FRAME_NUM: 2

SOLVER:
  IMS_PER_BATCH: 96
  BASE_LR: 0.0001
  STEPS: (70000, )
  MAX_ITER: 100000

