_BASE_: ../VLFormer_R101_bs4_100k.yaml
MODEL:
  WEIGHTS: scratch/hai/REFCOCO_all/model_0299999.pth #"https://dl.fbaipublicfiles.com/maskformer/video_mask2former/ytvis_2019/video_maskformer2_swin_base_IN21k_384_bs16_8ep/model_final_221a8a.pkl"
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
  IMS_PER_BATCH: 12
  STEPS: (100000, )
  MAX_ITER: 150000
