_BASE_: ../VLFormer_R101_bs4_100k.yaml
MODEL:
  BACKBONE:
    NAME: "VideoSwinTransformerBackbone"

  VIDEO_SWIN:
    VERSION: "video_swin_b_p4w7"

  WEIGHTS: "weights/video_swin_ytvis19.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

INPUT:
  MIN_SIZE_TEST: 480

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (25000, )
  MAX_ITER: 50000

  
